### ISSUE TITLE
Intended use scenario

### ISSUE THREAD

**Issue by livingentity** [FastCopyLab/FastCopy#26] opened 2022-02-02 09:22 UTC
What's the intended use case for FastCopy?
It seems this software was made for a special purpose and not for general moving/copying/syncing considering e.g. #15 and #24.

Also the 'delete before copying' option says it's deleting files that would otherwise be overwritten, too. Is there any benefit in deleting and copying over overwriting directly?

**Comment by auanasgheps** [comment] 2022-02-02 10:16
I love FastCopy: it's super fast and reliable.

Unfortunately the "sync" option is limited, like I described in #24. 
I use it to sync/backup my files from a PC to a NAS, however the lack of a "remote move" feature limits its potential a lot. 
I'll have to look for something else unfortunately.

**Comment by a-raccoon** [comment] 2022-02-02 14:27
> What's the intended use case for FastCopy? It seems this software was made for a special purpose and not for general moving/copying/syncing considering e.g. #15 and #24.
> 
> Also the 'delete before copying' option says it's deleting files that would otherwise be overwritten, too. Is there any benefit in deleting and copying over overwriting directly?

FastCopy has been around for some 20 years.  I've been using it all that time.  It's a Windows copy program, which there are a lot of now, that is/was superior to the default Windows copy as it can gracefully handle copy errors, rules for replacing existing files based on their size/date, and will preserve the Created Time property when copying files or moving them to another volume.  Best of all, though, is the verify feature which double checks the copy's integrity.  And also the removal of NTFS owner/security and ADS junk that taxi around with files that can make them difficult to access from other computers on a portable drive.

I estimate the "delete before copying" was intended for people who are writing large files to a nearly full volume or floppy disk, so there's room to accept the replacement file.

**Comment by auanasgheps** [comment] 2022-02-03 09:56
@a-raccoon 
> will preserve the Created Time property when copying files or moving them to another volume

You reminded me why I started using FastCopy in the first place! This was the reason!!!! 

> I use FastCopy daily, including batch processing weekly and monthly backups via Task Scheduler.
So you may have noticed one of it's biggest limitations: does not move files on the destination, deletes the file and copies it again.

**Comment by a-raccoon** [comment] 2022-02-03 10:08
> So you may have noticed one of it's biggest limitations: does not move files on the destination, deletes the file and copies it again.

I wouldn't call that a limitation.  It's a little bit more complicated, but what this boils down to is an issue of nomenclature, aka, common parlance.  So allow me to explain.

In the world of files saved in folders to a volume, there are two main operations you can perform on them.  Copy and Rename.  Actually three if we include Delete.  When you Copy a file, you create a duplicate of it.  When you rename a file, you either change the file's filename, or you change the name of the file's pathname.  We sometimes call the latter operation "Move."  Trust me, it's just a Rename.  UNLESS you "Move" a file from one volume (drive C) to another volume (drive E), then that isn't a Rename but instead it is a Copy + Delete.  Not a Move.  Remember, there is no Move, just Rename and Copy and Delete.

So, considering the above, what does FastCopy do?  Hint: It's in the name.

FastCopy does not do Rename operations.  Only Copy.

**Comment by PapaKarl0** [comment] 2022-02-04 00:56
I use FC to delete files because it can do that faster than other software. And, most importantly, it works with lists of files. I know it's not recommended but I feed it massive lists with millions of lines and it works just fine. I also use it to move files quickly in similar fashion. As for the renaming operation... I would definitely love to see it in the nearest future.

**Comment by a-raccoon** [comment] 2022-02-04 01:08
@PapaKarl0 check out Everything by Voidtools.  Especially the current 1.5 Alpha release.  It sports an Advanced Rename and Advanced Move, the latter which lets you rename a list of file's entire path and filename.  (It does Copy, too, but sends that off to Windows Explorer to handle.)

Eg, flatten: E:\Music\Pink Turtles\2014 Another Stone In The Pond\03 Hey Creature Leave Those Tadpoles Alone.mp3
to: E:\Music\Pink Turtles -- 2014 Another Stone In The Pond -- 03 Hey Creature Leave Those Tadpoles Alone.mp3

**Closed** 2022-02-04 06:45 UTC
Labels: question
